#!/usr/bin/python

import sys, hashlib, os, shlex, time, shutil, traceback
from subprocess import Popen, PIPE, STDOUT
from cache import PygmentizeCache, log

pygments_cache = PygmentizeCache()

pygmentize_cmd = pygments_cache.parse_pygmentizeargs(sys.argv)

try: 
    if not pygments_cache.contains_input_file(sys.argv):
        output = pygments_cache.fork_pygmentize_stdin(pygmentize_cmd)
        print output
    else:
        pygments_cache.find_from_cache_or_fork(pygmentize_cmd)
except Exception:
    exc_type, exc_value, exc_traceback = sys.exc_info()
    log("deu erro: " + pygmentize_cmd)
    log_file = open('/tmp/pygmentize-output', 'a')
    traceback.print_exception(exc_type, exc_value, exc_traceback, limit=10, file=log_file)
    log_file.close




