#!/usr/bin/python

import sys, hashlib, os, shlex, time, shutil, traceback
from subprocess import Popen, PIPE, STDOUT
from cache import PygmentizeCache, PygmentizeExecutor, log

pygments_cache = PygmentizeCache(sys.argv, PygmentizeExecutor())

try: 
    pygments_cache.execute()
        
except Exception:
    exc_type, exc_value, exc_traceback = sys.exc_info()
    log("deu erro: " + pygmentize_cmd)
    log_file = open('/tmp/pygmentize-output', 'a')
    traceback.print_exception(exc_type, exc_value, exc_traceback, limit=10, file=log_file)
    log_file.close




