#!/usr/bin/python

import sys
from subprocess import Popen, PIPE, STDOUT

def log(string):
    log = open('/tmp/pygmentize-output', 'a')
    log.write(string + "\n")
    log.close

def contains_input_file(args):
    contains =  not args[len(args) - 2].startswith("-")
    return contains

def read_code(args):
    f = open(args[len(args) - 1], 'r')
    return f.read()
    
def parse_pygmentizeargs(argv):
    pygmentize_cmd = "pygmentize-orig"
    for c in argv:
        if c == argv[0]:
            continue
        c = c.replace(" ", "")
        pygmentize_cmd += " " + c
    return pygmentize_cmd
    
def fork_pygmentize(pygmentize_cmd):
    p = Popen(pygmentize_cmd, shell=True, stdin=PIPE, stdout=PIPE, stderr=PIPE, close_fds=True)
    if not contains_input_file(sys.argv):
        stdin_input = sys.stdin.read()
        p.stdin.write(stdin_input)
        p.stdin.close()
    return p.stdout.read()
    

pygmentize_cmd = parse_pygmentizeargs(sys.argv)
output = fork_pygmentize(pygmentize_cmd)

log(pygmentize_cmd)
log(str(sys.argv))
log(output)

print output


